### PR TITLE
Fix additional edge cases

### LINKED ISSUE #30: ref properties are not correctly generated as `ref` interface members
Example:

```csharp
[GenerateAutomaticInterface]
public partial class Test : ITest
{
	private int _test = 5;
	public ref int Value => ref _test;
}
```

Generated code is

```csharp
[GeneratedCode("AutomaticInterface", "")]
    public partial interface ITest
    {
        /// <inheritdoc />
        int Value { get; }
        
    }
```

You will then get an error on member `Test.Value`: `cannot implement 'ITest.Value' because it does not return by value`

### PR DESCRIPTION
**Pull request by roflmuffin**
- Adds support for `ref` property generation
- Does a naive de-dupe on name to allow for overriding/new properties with the same name
- Uses syntax literal identifier text rather than name where possible, to allow for variable names with special symbols like `@event`

Closes #30, #31 & #32

### CODE REVIEW

**Comment by ChristianSauer** [comment]
Hi, this looks good to me. Nice findings.
Can you fix the formatting and the two failing tests?` #nullable enable/ #nullable restore are missing for some reason

**Comment by roflmuffin** [comment]
I have fixed the formatting, but it looks like those two failing tests are also failing in master; though I can take a look if you want?

**Comment by ChristianSauer** [comment]
I fixed them. Funny how that got into master.
Thanks a lot!
Will push this as a minor release

**Comment by ChristianSauer** [comment]
Ah, I think you need to pull master into your branch once. Sorry!

**Comment by roflmuffin** [comment]
Done, thanks for that! I would have fixed them but had issues with line endings on windows 10 with the tests :(

**Comment by ChristianSauer** [comment]
It's on nuget as 2.2.1
Thanks!

**Pull request merged**
